/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export default {
  plugins: ['@binary64'],
  rules: {
    '@binary64/formik-require-generic': 'error',
    '@binary64/classnames-require': 'error',
    '@binary64/react-consistent-usestate-naming': 'error',
    '@binary64/react-deprecate-fc': 'error',
  },
}
