/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
'use strict'

export = {
  configs: {
    recommended: require('./configs/recommended').default,
  },
  rules: {
    'formik-require-generic': require('./rules/formik-require-generic').default,
    'classnames-require': require('./rules/classnames-require').default,
    'react-consistent-usestate-naming': require('./rules/react-consistent-usestate-naming').default,
    'react-deprecate-fc': require('./rules/react-deprecate-fc').default,
  },
}
