/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
'use strict'

export = {
  configs: {
    recommended: import('./configs/recommended'),
  },
  rules: {
    'formik-require-generic': import('./rules/formik-require-generic'),
    'classnames-require': import('./rules/classnames-require'),
    'react-consistent-usestate-naming': import('./rules/react-consistent-usestate-naming'),
    'react-deprecate-fc': import('./rules/react-deprecate-fc'),
  },
}
